[GLOBAL]
pants_version = "2.21.0"

build_patterns = ["BUILD.pants", "BUILD"]
pantsd = true 
plugins = ["robotpajamas.pants.scie==0.0.3"]

backend_packages = [
    "pants.backend.python",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
    "experimental.scie"
]

[source]
marker_filenames = ["BUILD.pants"]

[python]
enable_resolves = true
interpreter_constraints = ["==3.9.*"]
tailor_pex_binary_targets = false

[python.resolves]
python-default = "build-support/lockfiles/python-default.lock"
simple = "build-support/lockfiles/simple.lock"
multipex = "build-support/lockfiles/multipex.lock"
multistage = "build-support/lockfiles/multistage.lock"

[stats]
log = false

[anonymous-telemetry]
enabled = false