__defaults__(all=dict(resolve="multistage"))

python_requirements(
    name="reqs",
)

python_sources(
    name="lib",
)

# pex_binary(
#     name="multistage-bin",
#     dependencies=[":lib"],
#     entry_point="main.py"
# )
